settings:

  debug-mode: true
  broadcast_rank_message: true
  permissions:
    rankup: command.rankup
    rankdown: command.rankdown

lang:
  error_message: "&cAn error has occurred, please contact the administrators."
  rankup_success: "&aYou have ranked up to rank &r%rank% &asuccessfully."
  rankup_broadcast: "&ePlayer &f%player% &eranked up to rank &f%rank% &esuccessfully."
  last_rankup: "&eYou are already at the last rank!"
  rankdown_error: "&cYou can't rankdown anymore!"
  rankdown_success: "&eYou have ranked down to rank &r%rank% &asuccessfully."
  requirements:
    playtime_need: "&cYou need %d% days, %h% hours, %m%, %s% seconds of playtime to be able to rankup."
    money_need: "&cYou need %money%$ to be able to rankup."
    message:
      - "&cCould not rankup, you are missing the following requirements:"
      - "%requirements%"

ranks:
  0: #Default rank
    display: ""
    permission: rank.default
    requirements:
      1:
        type: placeholder
        variable: ""
        return: money
        requirement: "2000" #<, <=, >, >=
      2:
        type: placeholder
        variable: ""
        return: playtime
        requirement: "2000" #(seconds) #<, <=, >, >=
    up_commands:
      - "CONSOLE;lp user $player parent add vip"
    down_commands:
      - "CONSOLE;lp user"
  1:
  2: