settings:

  debug-mode: true
  broadcast_rank_message: true
  permissions:
    rankup: command.rankup
    rankdown: command.rankdown

lang:
  error_message: "&cAn error has occurred, please contact the administrators."
  rankup_fail: "&cCould not rankup, you are missing the requirements."
  rankup_success: "&aYou have ranked up to rank &r%rank% &asuccessfully."
  rankup_broadcast: "&ePlayer &f%player% &eranked up to rank &f%rank% &esuccessfully."
  last_rankup: "&eYou are already at the last rank!"
  rankdown_error: "&cYou can't rankdown anymore!"
  rankdown_success: "&eYou have ranked down to rank &r%rank% &asuccessfully."

ranks:
  0: #Default rank
    display: ""
    permission: rank.default
    requirements:
      1:
        type: placeholder
        variable: ""
        return: integer
        requirement: ">=;2000" #<, <=, >, >=
    up_commands:
      - "CONSOLE;lp user $player parent add vip"
    down_commands:
      - "CONSOLE;lp user"
  1:
  2: